[pytest]

addopts = -vs --alluredir=./report/temp --clean-alluredir --junitxml=./report/junit.xml -W ignore::urllib3.exceptions.InsecureRequestWarning

testpaths = ./testcase

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
    error
    ignore::UserWarning

python_files = test_*.py

python_classes = Test*

python_functions = test_

markers =
    mayan: 冒烟测试
    danyuan: 单元测试
